### ISSUE TITLE
NVd+ sheath value incorrect

### ISSUE THREAD

**Issue by mikekryjak** [bendudson/hermes-3#237] opened 2024-07-24 16:58 UTC
I'm working on a 1D particle balance and trying to double check `sheath_boundary_simple` using `1D-recycling`, which has 100% recycling. I found that `NVd+` in the guard cell is set as if there is a `dirichlet(0)` boundary condition. 

This is incorrect. It also seems to be set by something other than `sheath_boundary_simple`, as the value is correct all the way through that component. I also tried disabling `no_flow_boundary` in case it had a bug in it, but to no avail.  

I'm not sure how I could test which component is overriding it in an easy way.

**Comment by bendudson** [comment] 2024-08-07 19:46
Unable to reproduce. Closing for now; re-open if problem reappears.

**Comment by mikekryjak** [comment] 2024-08-07 20:28
Hi @bendudson, here is 1D-recycling with CVODE and `sheath_boundary_simple` showing the problem:

![image](https://github.com/user-attachments/assets/7923b750-ef49-4d7f-a1e3-1b5af8f3f18e)
Maybe I'm misunderstanding something, but the guard cell here is the negative of the final domain cell, which is as if it's a `dirichlet(0)`.

My input file:
[input_file.txt](https://github.com/user-attachments/files/16533875/input_file.txt)

This is on latest master.

**Comment by bendudson** [comment] 2024-08-07 21:23
Running 
commit 3d3248f01162526e468b39c369f95c653230e87a
input file in examples/1D-recycling/cvode
after 400 outputs (t=1.2e5) I get:
```
In [5]: nvi[-1,0,-5:,0]
Out[5]: BoutArray([1.07370415, 1.15200512, 1.22180442, 1.30450176, 1.28690429])
```

**Comment by bendudson** [comment] 2024-08-07 23:41
Ah my bad: Forgot the `yguards=True` flag. I see the Dirichlet BC now (with sheath_boundary or sheath_boundary_simple)

**Comment by bendudson** [comment] 2024-08-07 23:55
I think the culprit is this line:
https://github.com/bendudson/hermes-3/blob/master/src/evolve_momentum.cxx#L205

This is needed for electromagnetic simulations: There the quantity evolved is the sum of momentum and an electromagnetic term. We need to restore this quantity so that restarting works correctly. The downside is that now the NV in the restart file does not contain the guard cells, and can be different from what is in the simulation.

**Comment by mikekryjak** [comment] 2024-08-08 13:04
I see. What do you think would be a good fix? Running the sheath BC for one evaluation after this is done? Is that feasible?

**Closed** 2024-08-15 15:25 UTC
Labels: bug
